### PR TITLE
updated grading

### PR DESCRIPTION
**Pull request by bwhm**
I updated the json for the website now, and quickly realized my schema isn't very good - almost 16k lines...

@DzhideX are you able to set your test deploy of the website point to my branch here?

### CODE REVIEW

**Review by DzhideX — APPROVED** [review]
I tested it locally and the .json file works great. (I think this is what you wanted, if not let me know!)

But there is a small thing I missed in the code that needs to be updated before this can be merged though!

**Comment by bwhm** [comment]
> I tested it locally and the .json file works great. (I think this is what you wanted, if not let me know!)

Yes, thanks :)

> But there is a small thing I missed in the code that needs to be updated before this can be merged though!

kk!

**Comment by bwhm** [comment]
Can you ping ben when ready?

**Comment by DzhideX** [comment]
As soon as that mentioned PR is merged, this one can also be merged. 

I set you as the reviewer but @blrhc can do it as well!

**Comment by bwhm** [comment]
Merging myself now!

**Pull request merged**
